### PR TITLE
Add missing 'or'

### PR DESCRIPTION
**Pull request by michael-simons**

### CODE REVIEW

**Comment by rdmueller** [comment]
thanx! Will create new template versions soon... please be patient.

**Comment by michael-simons** [comment]
No hurry. Just was reading through the docs. By the way, i've used the template here http://biking.michael-simons.eu/docs/index.html, full source available at my repository https://github.com/michael-simons/biking2.

**Comment by rdmueller** [comment]
just added your documentation to the "examples" section on http://arc42.github.io/ - hope this is ok :-)
Please send a PR if you want to have it changed...

**Comment by michael-simons** [comment]
Thanks, Ralf. I'm honored. The only fix: a typo, created instead of crated.

Am 22.12.2015 um 20:04 schrieb Ralf D. Müller <notifications@github.com>:

just added your documentation to the "examples" section on
http://arc42.github.io/ - hope this is ok :-)
Please send a PR if you want to have it changed...

—
Reply to this email directly or view it on GitHub
<https://github.com/arc42/arc42-template/pull/58#issuecomment-166704827>.

**Comment by rdmueller** [comment]
ok. thanx. fixed it...

**Pull request merged**
