### PR TITLE
Ru

### PR DESCRIPTION
**Pull request by max-arshinov**
Translation to Russian

### CODE REVIEW

**Comment by gernotstarke** [comment]
@max-arshinov - at first, let me thank you for your immense effort.

We already had a RU translation - as you can see in the git history. As the Ukrainian war started, we removed all ties to Russia from our repo, including the RU translation.

I'm currently torn between opening the template for Russians working in exile and keeping RU out due to the aggressive war in Ukraine.

Please be patient for a while - I will inquire with a few other contributors and collect their opinion.

@Hruschka @rdmueller what do you think?

**Comment by max-arshinov** [comment]
@gernotstarke thank you for the clarification. I should've checked the repo history. In any case, it was a rewarding experience as I had the opportunity to thoroughly study each section of the template.

I think I understand the motivation behind this decision. On the other hand, for all the banners that you guys added to the website and to the GitHub repo, without the Russian translation you show them to the non-Russian-speaking audience that, most likely, has already had a consensus about the war. Also, as you've already mentioned, the translation is still available in the repo history, so you don't really prevent war supporters from using it. As an alternative, the Russian translation can have an additional anti-war banner/text right in the template. I mean, even if 1% of the Russian-speaking audience changes their attitude, it's already better than 0. As of now, this communication channel is unavailable.

If the embedded banner idea makes sense, there is an additional non-trivial question. What kind of message can be written inside? The only one I can think of is that if the reader is an IT person and he/she cooperates with the Russian government (directly or indirectly), they should reconsider this decision. Of course it's not me to decide, I am just sharing what it looks like from a Russian-speaking person's perspective.

**Comment by gernotstarke** [comment]
thanx @max-arshinov again. I started a poll on LinkedIn and in the INNOQ internal Slack to collect arguments.
Until now many people in favour of a RU translation gave good arguments, people against it only voted but did not explain their decision...

You and some others nearly have me convinced to accept your PR, though... please let me sleep over it again and wait for additional comments on the channels mentioned above.

**Comment by rdmueller** [comment]
this is not an easy decision. I love having the template in as many languages as possible since I enjoy seeing it being used all over the world.
However, I also support the decision to act against the war.

How about this: can't we update the licence in such a way that it does not permit the use for military projects in general? Something like that? 

I know, people will still use it, but it would be a strong statement.

**Comment by gernotstarke** [comment]
I'll accept and merge your PR.

After several discussions and consultations with other people we (Peter Hruschka and myself) decided to offer a RU translation (again) - but updating our licence to restrict the RU usage to non-government and exile organizations.
We know that we can never check that.

I asked on LinkedIn, more than 70 people voted, 66% in favour of a RU translation.

Screenshot 2023-07-25 um 07 58 09

**Review by gernotstarke — APPROVED** [review]

**Comment by gernotstarke** [comment]
We have to generate the RU versions from asciidoc and add it (manually) to the download-section on arc42.org.

Will do that within the next couple of days - but I need to find an appropriate wording for the licence first.

thanx, @max-arshinov for your effort.

**Pull request merged**
