### PR TITLE
Spanish template use images with ES extension (copied from EN)

### PR DESCRIPTION
**Pull request by jakubjab**
I would like to add placeholders for Spanish images, so that when creating distribution zip file, we can only include files for specific language.

### CODE REVIEW

**Comment by gernotstarke** [comment]
this is imho a good idea - we didn't think of this issue before, sorry.

@jakubjab : what platform are you using - I could provide the original images and
you might be able to translate those to Spanish... Please let us know in a comment here.

**Comment by jakubjab** [comment]
@gernotstarke - unfortunatelly I don't know Spanish.
I think the easiest would be if that the original author of Spanish translation @isidorotrevino could just send you the translations string by string, and you could make Spanish version using the same tools as other versions.

**Comment by rdmueller** [comment]
I know someone with a mac who is spanish...

**Comment by xicu** [comment]
I'm an Spanish colleague of @jakubjab. I'd be pleased of helping on the translation of those strings.

For 05_building_blocks-ES.png:
* Scope and context: Alcance y contexto
* Neighbor system: Sistema vecino
* System: Sistema
* Administrator: Administrador
* Whitebox System X: Caja blanca del sistema X
* Refined (as new diagram): Refinado (como un nuevo diagrama)
* Level: Nivel

I can also work on 08-Crosscutting-Concepts-Structure-ES.png if you like the idea, or even create a pull-request as well.

Cheers

**Comment by gernotstarke** [comment]
Hi Xicu, welcome...

with commit 3c70c42 I added the original (OmniGraffle and Xmind) graphics,
so we can now maintain dedicated Spanish graphics...

OmniGraffle is a commercial Mac-OS tool,
Xmind a (free + commercial) mindmapper...

(I did not yet translate the graphics, just provided the originals)

**Comment by gernotstarke** [comment]
see also #103

**Pull request merged**
