### PR TITLE
GitHub-Flavored Markdown

### LINKED ISSUE #107: Add Template in Github Markdown
It would be nice to have a template in Github/GitLab markdown.

* Usage of Markdown, without the non supported extras currently used in the md packages
* Have "main file" of each chapter in a README.MD for a nice overview

This should be cool for github projects, who want to use markdown instead of asciidoc and for Gitlab users, since asciidoc is not supported there.

### PR DESCRIPTION
**Pull request by handcraftedsource**
Thank you for accepting my PullRequest for the generator. Of course the finished templates are still missing.

Generated the new GitHub flavored Markdown versions of the templates. 

Fixes #107

### CODE REVIEW

**Comment by rdmueller** [comment]
yes, that's still a manual task. Hope I can do it over the weekend...

**Comment by rdmueller** [comment]
sorry, have seen just now that this is a PR...

**Comment by handcraftedsource** [comment]
No problem. Thank you very much for accepting.

**Comment by rdmueller** [comment]
the templates are now available on github and I've seen the PR for the website... perfect!

btw: do you already take part in https://hacktoberfest.digitalocean.com/ ?

**Comment by handcraftedsource** [comment]
Yes, I'll take part. But in this case I even have a concrete benefit for our current project.

**Pull request merged**
