### PR TITLE
Added updated templates for Enterprise Architect.

### PR DESCRIPTION
**Pull request by raphael-dumhart**
Since the current Enterprise Architect format is very outdated, I wanted to create templates that are up-to-date.

This template is available in DE and EN and contains the full arc42 structure including diagrams and text heavy section. Explanations (content, motivation, etc.) are taken from the original AsciiDoc format and extended where necessary.

### CODE REVIEW

**Comment by gernotstarke** [comment]
Raphael, thanx for your contribution, highly appreciated!!

Could you please add a short "readme" on how to use these templates (I'm currently not using EA very often, and therefore unsure how to apply a "qea" file.

thanx
Gernot

**Comment by raphael-dumhart** [comment]
Sure! If you want to have any additional information in the readme, let me know.

**Comment by raphael-dumhart** [comment]
Hello @gernotstarke,

Sorry to bother you, but did you have a chance to check my PR?

Best regards,
Raphael

**Comment by gernotstarke** [comment]
my bad - your PR is awesome, but I did not yet take the time to update the downloads page...
(we're lacking automation here, sorry sorry sorry).

@rdmueller - could you possibly add the EA-template to downloads during the next few days?

**Comment by gernotstarke** [comment]
Raphael, would you be so kind and ALSO export your template in the (older) eap-format? Not all users of EA will have the latest (... I have only 15.2...)

thanx

**Comment by raphael-dumhart** [comment]
That's a fair point. I added an EAPX version of the template and explaint on how to deal with the file formats and EA version in the readme.

**Review by gernotstarke — APPROVED** [review]
Thank you so much!

**Comment by rdmueller** [comment]
> @rdmueller - could you possibly add the EA-template to downloads during the next few days?

@gernotstarke - you already did that, didn't you?
A blog post with some screenshots would be nice to link to...

**Comment by raphael-dumhart** [comment]
@rdmueller You mean something like this? 😉

https://www.raphaeldumhart.at/blog/arc42-template-enterprise-architect/

I just finsihed it today and it's only available in German. If I find some time I'll translate it to English, but this might take a while.

**Pull request merged**
