### PR TITLE
Italian template translation

### PR DESCRIPTION
**Pull request by mgiustiniani**
Hi, 

I translated the template into the Italian language,
if you want to add it to official repository, i would appreciate it.

regards

### CODE REVIEW

**Comment by rdmueller** [comment]
wow. that's cool! Please allow us some time to check it out before we merge the PR.

**Comment by rdmueller** [comment]
@mgiustiniani - quick question - for the distribution, did you use the arc42-generator project?

**Comment by mgiustiniani** [comment]
yes, but I only committed the IT versions

**Comment by rdmueller** [comment]
perfect. thanx!

**Pull request merged**
